export const LANGUAGES = [
    { code: "aa", name: "Afar" },
    { code: "aa-DJ", name: "Afar (Djibouti)" },
    { code: "aa-ER", name: "Afar (Eritrea)" },
    { code: "ab", name: "Abkhazian" },
    { code: "af", name: "Afrikaans" },
    { code: "af-NA", name: "Afrikaans (Namibia)" },
    { code: "ak", name: "Akan" },
    { code: "am", name: "Amharic" },
    { code: "an", name: "Aragonese" },
    { code: "ar", name: "Arabic" },
    { code: "ar-AE", name: "Arabic (United Arab Emirates)" },
    { code: "ar-BH", name: "Arabic (Bahrain)" },
    { code: "ar-DJ", name: "Arabic (Djibouti)" },
    { code: "ar-DZ", name: "Arabic (Algeria)" },
    { code: "ar-EG", name: "Arabic (Egypt)" },
    { code: "ar-EH", name: "Arabic (Western Sahara)" },
    { code: "ar-ER", name: "Arabic (Eritrea)" },
    { code: "ar-IL", name: "Arabic (Israel)" },
    { code: "ar-IQ", name: "Arabic (Iraq)" },
    { code: "ar-JO", name: "Arabic (Jordan)" },
    { code: "ar-KM", name: "Arabic (Comoros)" },
    { code: "ar-KW", name: "Arabic (Kuwait)" },
    { code: "ar-LB", name: "Arabic (Lebanon)" },
    { code: "ar-LY", name: "Arabic (Libya)" },
    { code: "ar-MA", name: "Arabic (Morocco)" },
    { code: "ar-MR", name: "Arabic (Mauritania)" },
    { code: "ar-OM", name: "Arabic (Oman)" },
    { code: "ar-PS", name: "Arabic (Palestinian Territories)" },
    { code: "ar-QA", name: "Arabic (Qatar)" },
    { code: "ar-SA", name: "Arabic (Saudi Arabia)" },
    { code: "ar-SD", name: "Arabic (Sudan)" },
    { code: "ar-SO", name: "Arabic (Somalia)" },
    { code: "ar-SS", name: "Arabic (South Sudan)" },
    { code: "ar-SY", name: "Arabic (Syria)" },
    { code: "ar-TD", name: "Arabic (Chad)" },
    { code: "ar-TN", name: "Arabic (Tunisia)" },
    { code: "ar-YE", name: "Arabic (Yemen)" },
    { code: "as", name: "Assamese" },
    { code: "az", name: "Azerbaijani" },
    { code: "az-Arab", name: "Azerbaijani (Arabic script)" },
    { code: "az-Arab-IQ", name: "Azerbaijani (Iraq, Arabic script)" },
    { code: "az-Arab-TR", name: "Azerbaijani (Turkey, Arabic script)" },
    { code: "az-Cyrl", name: "Azerbaijani (Cyrillic script)" },
    { code: "az-Latn", name: "Azerbaijani (Latin script)" },
    { code: "ba", name: "Bashkir" },
    { code: "be", name: "Belarusian" },
    { code: "be-tarask", name: "Belarusian (Taraškievica)" },
    { code: "bg", name: "Bulgarian" },
    { code: "bg-BG", name: "Bulgarian (Bulgaria)" },
    { code: "bm", name: "Bambara" },
    { code: "bm-Nkoo", name: "Bambara (N'Ko script)" },
    { code: "bn", name: "Bengali" },
    { code: "bn-IN", name: "Bengali (India)" },
    { code: "bo", name: "Tibetan" },
    { code: "bo-IN", name: "Tibetan (India)" },
    { code: "br", name: "Breton" },
    { code: "bs", name: "Bosnian" },
    { code: "bs-Cyrl", name: "Bosnian (Cyrillic script)" },
    { code: "bs-Latn", name: "Bosnian (Latin script)" },
    { code: "ca", name: "Catalan" },
    { code: "ca-AD", name: "Catalan (Andorra)" },
    { code: "ca-ES", name: "Catalan (Spain)" },
    { code: "ca-FR", name: "Catalan (France)" },
    { code: "ca-IT", name: "Catalan (Italy)" },
    { code: "ce", name: "Chechen" },
    { code: "co", name: "Corsican" },
    { code: "cs", name: "Czech" },
    { code: "cs-CZ", name: "Czech (Czechia)" },
    { code: "cv", name: "Chuvash" },
    { code: "cy", name: "Welsh" },
    { code: "da", name: "Danish" },
    { code: "da-DK", name: "Danish (Denmark)" },
    { code: "da-GL", name: "Danish (Greenland)" },
    { code: "de", name: "German" },
    { code: "de-AT", name: "German (Austria)" },
    { code: "de-BE", name: "German (Belgium)" },
    { code: "de-CH", name: "German (Switzerland)" },
    { code: "de-DE", name: "German (Germany)" },
    { code: "de-IT", name: "German (Italy)" },
    { code: "de-LI", name: "German (Liechtenstein)" },
    { code: "de-LU", name: "German (Luxembourg)" },
    { code: "dv", name: "Divehi" },
    { code: "dz", name: "Dzongkha" },
    { code: "ee", name: "Ewe" },
    { code: "ee-TG", name: "Ewe (Togo)" },
    { code: "el", name: "Greek" },
    { code: "el-CY", name: "Greek (Cyprus)" },
    { code: "el-GR", name: "Greek (Greece)" },
    { code: "el-polyton", name: "Greek (Polytonic)" },
    { code: "en", name: "English" },
    { code: "en-AE", name: "English (United Arab Emirates)" },
    { code: "en-AG", name: "English (Antigua & Barbuda)" },
    { code: "en-AI", name: "English (Anguilla)" },
    { code: "en-AS", name: "English (American Samoa)" },
    { code: "en-AT", name: "English (Austria)" },
    { code: "en-AU", name: "English (Australia)" },
    { code: "en-BB", name: "English (Barbados)" },
    { code: "en-BE", name: "English (Belgium)" },
    { code: "en-BI", name: "English (Burundi)" },
    { code: "en-BM", name: "English (Bermuda)" },
    { code: "en-BS", name: "English (Bahamas)" },
    { code: "en-BW", name: "English (Botswana)" },
    { code: "en-BZ", name: "English (Belize)" },
    { code: "en-CA", name: "English (Canada)" },
    { code: "en-CC", name: "English (Cocos [Keeling] Islands)" },
    { code: "en-CH", name: "English (Switzerland)" },
    { code: "en-CK", name: "English (Cook Islands)" },
    { code: "en-CM", name: "English (Cameroon)" },
    { code: "en-CX", name: "English (Christmas Island)" },
    { code: "en-CY", name: "English (Cyprus)" },
    { code: "en-CZ", name: "English (Czechia)" },
    { code: "en-DE", name: "English (Germany)" },
    { code: "en-DG", name: "English (Diego Garcia)" },
    { code: "en-DK", name: "English (Denmark)" },
    { code: "en-DM", name: "English (Dominica)" },
    { code: "en-ER", name: "English (Eritrea)" },
    { code: "en-ES", name: "English (Spain)" },
    { code: "en-FI", name: "English (Finland)" },
    { code: "en-FJ", name: "English (Fiji)" },
    { code: "en-FK", name: "English (Falkland Islands)" },
    { code: "en-FM", name: "English (Micronesia)" },
    { code: "en-FR", name: "English (France)" },
    { code: "en-GB", name: "English (United Kingdom)" },
    { code: "en-GD", name: "English (Grenada)" },
    { code: "en-GG", name: "English (Guernsey)" },
    { code: "en-GH", name: "English (Ghana)" },
    { code: "en-GI", name: "English (Gibraltar)" },
    { code: "en-GM", name: "English (Gambia)" },
    { code: "en-GS", name: "English (South Georgia & South Sandwich Islands)" },
    { code: "en-GU", name: "English (Guam)" },
    { code: "en-GY", name: "English (Guyana)" },
    { code: "en-HK", name: "English (Hong Kong SAR China)" },
    { code: "en-HU", name: "English (Hungary)" },
    { code: "en-ID", name: "English (Indonesia)" },
    { code: "en-IE", name: "English (Ireland)" },
    { code: "en-IL", name: "English (Israel)" },
    { code: "en-IM", name: "English (Isle of Man)" },
    { code: "en-IN", name: "English (India)" },
    { code: "en-IO", name: "English (British Indian Ocean Territory)" },
    { code: "en-IT", name: "English (Italy)" },
    { code: "en-JE", name: "English (Jersey)" },
    { code: "en-JM", name: "English (Jamaica)" },
    { code: "en-KE", name: "English (Kenya)" },
    { code: "en-KI", name: "English (Kiribati)" },
    { code: "en-KN", name: "English (St. Kitts & Nevis)" },
    { code: "en-KY", name: "English (Cayman Islands)" },
    { code: "en-LC", name: "English (St. Lucia)" },
    { code: "en-LR", name: "English (Liberia)" },
    { code: "en-LS", name: "English (Lesotho)" },
    { code: "en-MG", name: "English (Madagascar)" },
    { code: "en-MH", name: "English (Marshall Islands)" },
    { code: "en-MO", name: "English (Macao SAR China)" },
    { code: "en-MP", name: "English (Northern Mariana Islands)" },
    { code: "en-MS", name: "English (Montserrat)" },
    { code: "en-MT", name: "English (Malta)" },
    { code: "en-MU", name: "English (Mauritius)" },
    { code: "en-MV", name: "English (Maldives)" },
    { code: "en-MW", name: "English (Malawi)" },
    { code: "en-MY", name: "English (Malaysia)" },
    { code: "en-NA", name: "English (Namibia)" },
    { code: "en-NF", name: "English (Norfolk Island)" },
    { code: "en-NG", name: "English (Nigeria)" },
    { code: "en-NL", name: "English (Netherlands)" },
    { code: "en-NO", name: "English (Norway)" },
    { code: "en-NR", name: "English (Nauru)" },
    { code: "en-NU", name: "English (Niue)" },
    { code: "en-NZ", name: "English (New Zealand)" },
    { code: "en-PG", name: "English (Papua New Guinea)" },
    { code: "en-PH", name: "English (Philippines)" },
    { code: "en-PK", name: "English (Pakistan)" },
    { code: "en-PL", name: "English (Poland)" },
    { code: "en-PN", name: "English (Pitcairn Islands)" },
    { code: "en-PR", name: "English (Puerto Rico)" },
    { code: "en-PT", name: "English (Portugal)" },
    { code: "en-PW", name: "English (Palau)" },
    { code: "en-RO", name: "English (Romania)" },
    { code: "en-RW", name: "English (Rwanda)" },
    { code: "en-SB", name: "English (Solomon Islands)" },
    { code: "en-SC", name: "English (Seychelles)" },
    { code: "en-SD", name: "English (Sudan)" },
    { code: "en-SE", name: "English (Sweden)" },
    { code: "en-SG", name: "English (Singapore)" },
    { code: "en-SH", name: "English (St. Helena)" },
    { code: "en-SI", name: "English (Slovenia)" },
    { code: "en-SK", name: "English (Slovakia)" },
    { code: "en-SL", name: "English (Sierra Leone)" },
    { code: "en-SS", name: "English (South Sudan)" },
    { code: "en-SX", name: "English (Sint Maarten)" },
    { code: "en-SZ", name: "English (Eswatini)" },
    { code: "en-TC", name: "English (Turks & Caicos Islands)" },
    { code: "en-TK", name: "English (Tokelau)" },
    { code: "en-TO", name: "English (Tonga)" },
    { code: "en-TT", name: "English (Trinidad & Tobago)" },
    { code: "en-TV", name: "English (Tuvalu)" },
    { code: "en-TZ", name: "English (Tanzania)" },
    { code: "en-UG", name: "English (Uganda)" },
    { code: "en-UM", name: "English (U.S. Outlying Islands)" },
    { code: "en-VC", name: "English (St. Vincent & Grenadines)" },
    { code: "en-VG", name: "English (British Virgin Islands)" },
    { code: "en-VI", name: "English (U.S. Virgin Islands)" },
    { code: "en-VU", name: "English (Vanuatu)" },
    { code: "en-WS", name: "English (Samoa)" },
    { code: "en-ZA", name: "English (South Africa)" },
    { code: "en-ZM", name: "English (Zambia)" },
    { code: "en-ZW", name: "English (Zimbabwe)" },
    { code: "eo", name: "Esperanto" },
    { code: "es", name: "Spanish" },
    { code: "es-AR", name: "Spanish (Argentina)" },
    { code: "es-BO", name: "Spanish (Bolivia)" },
    { code: "es-BR", name: "Spanish (Brazil)" },
    { code: "es-BZ", name: "Spanish (Belize)" },
    { code: "es-CL", name: "Spanish (Chile)" },
    { code: "es-CO", name: "Spanish (Colombia)" },
    { code: "es-CR", name: "Spanish (Costa Rica)" },
    { code: "es-CU", name: "Spanish (Cuba)" },
    { code: "es-DO", name: "Spanish (Dominican Republic)" },
    { code: "es-EA", name: "Spanish (Ceuta & Melilla)" },
    { code: "es-EC", name: "Spanish (Ecuador)" },
    { code: "es-ES", name: "Spanish (Spain)" },
    { code: "es-GQ", name: "Spanish (Equatorial Guinea)" },
    { code: "es-GT", name: "Spanish (Guatemala)" },
    { code: "es-HN", name: "Spanish (Honduras)" },
    { code: "es-IC", name: "Spanish (Canary Islands)" },
    { code: "es-MX", name: "Spanish (Mexico)" },
    { code: "es-NI", name: "Spanish (Nicaragua)" },
    { code: "es-PA", name: "Spanish (Panama)" },
    { code: "es-PE", name: "Spanish (Peru)" },
    { code: "es-PH", name: "Spanish (Philippines)" },
    { code: "es-PR", name: "Spanish (Puerto Rico)" },
    { code: "es-PY", name: "Spanish (Paraguay)" },
    { code: "es-SV", name: "Spanish (El Salvador)" },
    { code: "es-US", name: "Spanish (United States)" },
    { code: "es-UY", name: "Spanish (Uruguay)" },
    { code: "es-VE", name: "Spanish (Venezuela)" },
    { code: "et", name: "Estonian" },
    { code: "et-EE", name: "Estonian (Estonia)" },
    { code: "eu", name: "Basque" },
    { code: "fa", name: "Persian" },
    { code: "fa-AF", name: "Persian (Afghanistan)" },
    { code: "fa-IR", name: "Persian (Iran)" },
    { code: "ff", name: "Fulah" },
    { code: "ff-Adlm", name: "Fulah (Adlam script)" },
    { code: "ff-Adlm-BF", name: "Fulah (Burkina Faso, Adlam script)" },
    { code: "ff-Adlm-CM", name: "Fulah (Cameroon, Adlam script)" },
    { code: "ff-Adlm-GH", name: "Fulah (Ghana, Adlam script)" },
    { code: "ff-Adlm-GM", name: "Fulah (Gambia, Adlam script)" },
    { code: "ff-Adlm-GW", name: "Fulah (Guinea-Bissau, Adlam script)" },
    { code: "ff-Adlm-LR", name: "Fulah (Liberia, Adlam script)" },
    { code: "ff-Adlm-MR", name: "Fulah (Mauritania, Adlam script)" },
    { code: "ff-Adlm-NE", name: "Fulah (Niger, Adlam script)" },
    { code: "ff-Adlm-NG", name: "Fulah (Nigeria, Adlam script)" },
    { code: "ff-Adlm-SL", name: "Fulah (Sierra Leone, Adlam script)" },
    { code: "ff-Adlm-SN", name: "Fulah (Senegal, Adlam script)" },
    { code: "ff-Latn", name: "Fulah (Latin script)" },
    { code: "ff-Latn-BF", name: "Fulah (Burkina Faso, Latin script)" },
    { code: "ff-Latn-CM", name: "Fulah (Cameroon, Latin script)" },
    { code: "ff-Latn-GH", name: "Fulah (Ghana, Latin script)" },
    { code: "ff-Latn-GM", name: "Fulah (Gambia, Latin script)" },
    { code: "ff-Latn-GN", name: "Fulah (Guinea, Latin script)" },
    { code: "ff-Latn-GW", name: "Fulah (Guinea-Bissau, Latin script)" },
    { code: "ff-Latn-LR", name: "Fulah (Liberia, Latin script)" },
    { code: "ff-Latn-MR", name: "Fulah (Mauritania, Latin script)" },
    { code: "ff-Latn-NE", name: "Fulah (Niger, Latin script)" },
    { code: "ff-Latn-NG", name: "Fulah (Nigeria, Latin script)" },
    { code: "ff-Latn-SL", name: "Fulah (Sierra Leone, Latin script)" },
    { code: "fi", name: "Finnish" },
    { code: "fi-FI", name: "Finnish (Finland)" },
    { code: "fil-PH", name: "Filipino (Philippines)" },
    { code: "fo", name: "Faroese" },
    { code: "fo-DK", name: "Faroese (Denmark)" },
    { code: "fr", name: "French" },
    { code: "fr-BE", name: "French (Belgium)" },
    { code: "fr-BF", name: "French (Burkina Faso)" },
    { code: "fr-BI", name: "French (Burundi)" },
    { code: "fr-BJ", name: "French (Benin)" },
    { code: "fr-BL", name: "French (St. Barthélemy)" },
    { code: "fr-CA", name: "French (Canada)" },
    { code: "fr-CD", name: "French (Congo - Kinshasa)" },
    { code: "fr-CF", name: "French (Central African Republic)" },
    { code: "fr-CG", name: "French (Congo - Brazzaville)" },
    { code: "fr-CH", name: "French (Switzerland)" },
    { code: "fr-CI", name: "French (Côte d’Ivoire)" },
    { code: "fr-CM", name: "French (Cameroon)" },
    { code: "fr-DJ", name: "French (Djibouti)" },
    { code: "fr-DZ", name: "French (Algeria)" },
    { code: "fr-FR", name: "French (France)" },
    { code: "fr-GA", name: "French (Gabon)" },
    { code: "fr-GF", name: "French (French Guiana)" },
    { code: "fr-GN", name: "French (Guinea)" },
    { code: "fr-GP", name: "French (Guadeloupe)" },
    { code: "fr-GQ", name: "French (Equatorial Guinea)" },
    { code: "fr-HT", name: "French (Haiti)" },
    { code: "fr-KM", name: "French (Comoros)" },
    { code: "fr-LU", name: "French (Luxembourg)" },
    { code: "fr-MA", name: "French (Morocco)" },
    { code: "fr-MC", name: "French (Monaco)" },
    { code: "fr-MF", name: "French (St. Martin)" },
    { code: "fr-MG", name: "French (Madagascar)" },
    { code: "fr-ML", name: "French (Mali)" },
    { code: "fr-MQ", name: "French (Martinique)" },
    { code: "fr-MR", name: "French (Mauritania)" },
    { code: "fr-MU", name: "French (Mauritius)" },
    { code: "fr-NC", name: "French (New Caledonia)" },
    { code: "fr-NE", name: "French (Niger)" },
    { code: "fr-PF", name: "French (French Polynesia)" },
    { code: "fr-PM", name: "French (St. Pierre & Miquelon)" },
    { code: "fr-RE", name: "French (Réunion)" },
    { code: "fr-RW", name: "French (Rwanda)" },
    { code: "fr-SC", name: "French (Seychelles)" },
    { code: "fr-SN", name: "French (Senegal)" },
    { code: "fr-SY", name: "French (Syria)" },
    { code: "fr-TD", name: "French (Chad)" },
    { code: "fr-TG", name: "French (Togo)" },
    { code: "fr-TN", name: "French (Tunisia)" },
    { code: "fr-VU", name: "French (Vanuatu)" },
    { code: "fr-WF", name: "French (Wallis & Futuna)" },
    { code: "fr-YT", name: "French (Mayotte)" },
    { code: "fy", name: "Western Frisian" },
    { code: "ga", name: "Irish" },
    { code: "ga-GB", name: "Irish (United Kingdom)" },
    { code: "gd", name: "Scottish Gaelic" },
    { code: "gl", name: "Galician" },
    { code: "gn", name: "Guarani" },
    { code: "gu", name: "Gujarati" },
    { code: "gu-IN", name: "Gujarati (India)" },
    { code: "gv", name: "Manx" },
    { code: "ha", name: "Hausa" },
    { code: "ha-Arab", name: "Hausa (Arabic script)" },
    { code: "ha-Arab-SD", name: "Hausa (Sudan, Arabic script)" },
    { code: "ha-GH", name: "Hausa (Ghana)" },
    { code: "ha-NE", name: "Hausa (Niger)" },
    { code: "he", name: "Hebrew" },
    { code: "he-IL", name: "Hebrew (Israel)" },
    { code: "hi", name: "Hindi" },
    { code: "hi-IN", name: "Hindi (India)" },
    { code: "hi-Latn", name: "Hindi (Latin script)" },
    { code: "hr", name: "Croatian" },
    { code: "hr-BA", name: "Croatian (Bosnia & Herzegovina)" },
    { code: "hr-HR", name: "Croatian (Croatia)" },
    { code: "ht", name: "Haitian" },
    { code: "hu", name: "Hungarian" },
    { code: "hu-HU", name: "Hungarian (Hungary)" },
    { code: "hy", name: "Armenian" },
    { code: "ia", name: "Interlingua" },
    { code: "id", name: "Indonesian" },
    { code: "id-ID", name: "Indonesian (Indonesia)" },
    { code: "ie", name: "Interlingue" },
    { code: "ig", name: "Igbo" },
    { code: "ii", name: "Sichuan Yi" },
    { code: "ik", name: "Inupiaq" },
    { code: "io", name: "Ido" },
    { code: "is", name: "Icelandic" },
    { code: "it", name: "Italian" },
    { code: "it-CH", name: "Italian (Switzerland)" },
    { code: "it-IT", name: "Italian (Italy)" },
    { code: "it-SM", name: "Italian (San Marino)" },
    { code: "it-VA", name: "Italian (Vatican City)" },
    { code: "iu", name: "Inuktitut" },
    { code: "iu-Latn", name: "Inuktitut (Latin script)" },
    { code: "ja", name: "Japanese" },
    { code: "ja-JP", name: "Japanese (Japan)" },
    { code: "jv", name: "Javanese" },
    { code: "ka", name: "Georgian" },
    { code: "ki", name: "Kikuyu" },
    { code: "kk", name: "Kazakh" },
    { code: "kk-Arab", name: "Kazakh (Arabic script)" },
    { code: "kk-Cyrl", name: "Kazakh (Cyrillic script)" },
    { code: "kk-KZ", name: "Kazakh (Kazakhstan)" },
    { code: "kl", name: "Kalaallisut" },
    { code: "km", name: "Central Khmer" },
    { code: "kn", name: "Kannada" },
    { code: "kn-IN", name: "Kannada (India)" },
    { code: "ko", name: "Korean" },
    { code: "ko-CN", name: "Korean (China)" },
    { code: "ko-KP", name: "Korean (North Korea)" },
    { code: "ko-KR", name: "Korean (South Korea)" },
    { code: "ks", name: "Kashmiri" },
    { code: "ks-Arab", name: "Kashmiri (Arabic script)" },
    { code: "ks-Deva", name: "Kashmiri (Devanagari script)" },
    { code: "ku", name: "Kurdish" },
    { code: "kw", name: "Cornish" },
    { code: "ky", name: "Kyrgyz" },
    { code: "la", name: "Latin" },
    { code: "lb", name: "Luxembourgish" },
    { code: "lg", name: "Ganda" },
    { code: "ln", name: "Lingala" },
    { code: "ln-AO", name: "Lingala (Angola)" },
    { code: "ln-CF", name: "Lingala (Central African Republic)" },
    { code: "ln-CG", name: "Lingala (Congo - Brazzaville)" },
    { code: "lo", name: "Lao" },
    { code: "lt", name: "Lithuanian" },
    { code: "lt-LT", name: "Lithuanian (Lithuania)" },
    { code: "lu", name: "Luba-Katanga" },
    { code: "lv", name: "Latvian" },
    { code: "lv-LV", name: "Latvian (Latvia)" },
    { code: "mg", name: "Malagasy" },
    { code: "mi", name: "Maori" },
    { code: "mk", name: "Macedonian" },
    { code: "ml", name: "Malayalam" },
    { code: "ml-IN", name: "Malayalam (India)" },
    { code: "mn", name: "Mongolian" },
    { code: "mn-Mong", name: "Mongolian (Mongolian script)" },
    { code: "mn-Mong-MN", name: "Mongolian (Mongolia, Mongolian script)" },
    { code: "mr", name: "Marathi" },
    { code: "mr-IN", name: "Marathi (India)" },
    { code: "ms", name: "Malay" },
    { code: "ms-Arab", name: "Malay (Arabic script)" },
    { code: "ms-Arab-BN", name: "Malay (Brunei, Arabic script)" },
    { code: "ms-BN", name: "Malay (Brunei)" },
    { code: "ms-ID", name: "Malay (Indonesia)" },
    { code: "ms-SG", name: "Malay (Singapore)" },
    { code: "mt", name: "Maltese" },
    { code: "my", name: "Burmese" },
    { code: "nb", name: "Norwegian Bokmål" },
    { code: "nb-SJ", name: "Norwegian Bokmål (Svalbard & Jan Mayen)" },
    { code: "nd", name: "North Ndebele" },
    { code: "ne", name: "Nepali" },
    { code: "ne-IN", name: "Nepali (India)" },
    { code: "nl", name: "Dutch" },
    { code: "nl-AW", name: "Dutch (Aruba)" },
    { code: "nl-BE", name: "Dutch (Belgium)" },
    { code: "nl-BQ", name: "Dutch (Caribbean Netherlands)" },
    { code: "nl-CW", name: "Dutch (Curaçao)" },
    { code: "nl-NL", name: "Dutch (Netherlands)" },
    { code: "nl-SR", name: "Dutch (Suriname)" },
    { code: "nl-SX", name: "Dutch (Sint Maarten)" },
    { code: "nn", name: "Norwegian Nynorsk" },
    { code: "no", name: "Norwegian" },
    { code: "no-NO", name: "Norwegian (Norway)" },
    { code: "nr", name: "South Ndebele" },
    { code: "nv", name: "Navajo" },
    { code: "ny", name: "Chichewa" },
    { code: "oc", name: "Occitan" },
    { code: "oc-ES", name: "Occitan (Spain)" },
    { code: "om", name: "Oromo" },
    { code: "om-KE", name: "Oromo (Kenya)" },
    { code: "or", name: "Oriya" },
    { code: "os", name: "Ossetian" },
    { code: "os-RU", name: "Ossetian (Russia)" },
    { code: "pa", name: "Punjabi" },
    { code: "pa-IN", name: "Punjabi (India)" },
    { code: "pa-Arab", name: "Punjabi (Arabic script)" },
    { code: "pa-Guru", name: "Punjabi (Gurmukhi script)" },
    { code: "pl", name: "Polish" },
    { code: "pl-PL", name: "Polish (Poland)" },
    { code: "ps", name: "Pashto" },
    { code: "ps-PK", name: "Pashto (Pakistan)" },
    { code: "pt", name: "Portuguese" },
    { code: "pt-AO", name: "Portuguese (Angola)" },
    { code: "pt-BR", name: "Portuguese (Brazil)" },
    { code: "pt-CH", name: "Portuguese (Switzerland)" },
    { code: "pt-CV", name: "Portuguese (Cape Verde)" },
    { code: "pt-GQ", name: "Portuguese (Equatorial Guinea)" },
    { code: "pt-GW", name: "Portuguese (Guinea-Bissau)" },
    { code: "pt-LU", name: "Portuguese (Luxembourg)" },
    { code: "pt-MO", name: "Portuguese (Macao SAR China)" },
    { code: "pt-MZ", name: "Portuguese (Mozambique)" },
    { code: "pt-PT", name: "Portuguese (Portugal)" },
    { code: "pt-ST", name: "Portuguese (São Tomé & Príncipe)" },
    { code: "pt-TL", name: "Portuguese (Timor-Leste)" },
    { code: "qu", name: "Quechua" },
    { code: "qu-BO", name: "Quechua (Bolivia)" },
    { code: "qu-EC", name: "Quechua (Ecuador)" },
    { code: "rm", name: "Romansh" },
    { code: "rn", name: "Rundi" },
    { code: "ro", name: "Romanian" },
    { code: "ro-MD", name: "Romanian (Moldova)" },
    { code: "ro-RO", name: "Romanian (Romania)" },
    { code: "ru", name: "Russian" },
    { code: "ru-BY", name: "Russian (Belarus)" },
    { code: "ru-KG", name: "Russian (Kyrgyzstan)" },
    { code: "ru-KZ", name: "Russian (Kazakhstan)" },
    { code: "ru-MD", name: "Russian (Moldova)" },
    { code: "ru-RU", name: "Russian (Russia)" },
    { code: "ru-UA", name: "Russian (Ukraine)" },
    { code: "rw", name: "Kinyarwanda" },
    { code: "sa", name: "Sanskrit" },
    { code: "sc", name: "Sardinian" },
    { code: "sd", name: "Sindhi" },
    { code: "sd-Arab", name: "Sindhi (Arabic script)" },
    { code: "sd-Deva", name: "Sindhi (Devanagari script)" },
    { code: "se", name: "Northern Sami" },
    { code: "se-FI", name: "Northern Sami (Finland)" },
    { code: "se-SE", name: "Northern Sami (Sweden)" },
    { code: "sg", name: "Sango" },
    { code: "si", name: "Sinhala" },
    { code: "sk", name: "Slovak" },
    { code: "sk-SK", name: "Slovak (Slovakia)" },
    { code: "sl", name: "Slovenian" },
    { code: "sl-SI", name: "Slovenian (Slovenia)" },
    { code: "sn", name: "Shona" },
    { code: "so", name: "Somali" },
    { code: "so-DJ", name: "Somali (Djibouti)" },
    { code: "so-ET", name: "Somali (Ethiopia)" },
    { code: "so-KE", name: "Somali (Kenya)" },
    { code: "sq", name: "Albanian" },
    { code: "sq-MK", name: "Albanian (North Macedonia)" },
    { code: "sq-XK", name: "Albanian (Kosovo)" },
    { code: "sr", name: "Serbian" },
    { code: "sr-RS", name: "Serbian (Serbia)" },
    { code: "sr-Cyrl", name: "Serbian (Cyrillic script)" },
    { code: "sr-Cyrl-BA", name: "Serbian (Bosnia & Herzegovina, Cyrillic script)" },
    { code: "sr-Cyrl-ME", name: "Serbian (Montenegro, Cyrillic script)" },
    { code: "sr-Cyrl-XK", name: "Serbian (Kosovo, Cyrillic script)" },
    { code: "sr-Latn", name: "Serbian (Latin script)" },
    { code: "sr-Latn-BA", name: "Serbian (Bosnia & Herzegovina, Latin script)" },
    { code: "sr-Latn-ME", name: "Serbian (Montenegro, Latin script)" },
    { code: "sr-Latn-XK", name: "Serbian (Kosovo, Latin script)" },
    { code: "ss", name: "Swati" },
    { code: "ss-SZ", name: "Swati (Eswatini)" },
    { code: "st", name: "Southern Sotho" },
    { code: "st-LS", name: "Southern Sotho (Lesotho)" },
    { code: "su", name: "Sundanese" },
    { code: "su-Latn", name: "Sundanese (Latin script)" },
    { code: "sv", name: "Swedish" },
    { code: "sv-AX", name: "Swedish (Åland Islands)" },
    { code: "sv-FI", name: "Swedish (Finland)" },
    { code: "sv-SE", name: "Swedish (Sweden)" },
    { code: "sw", name: "Swahili" },
    { code: "sw-CD", name: "Swahili (Congo - Kinshasa)" },
    { code: "sw-KE", name: "Swahili (Kenya)" },
    { code: "sw-TZ", name: "Swahili (Tanzania)" },
    { code: "sw-UG", name: "Swahili (Uganda)" },
    { code: "ta", name: "Tamil" },
    { code: "ta-IN", name: "Tamil (India)" },
    { code: "ta-LK", name: "Tamil (Sri Lanka)" },
    { code: "ta-MY", name: "Tamil (Malaysia)" },
    { code: "ta-SG", name: "Tamil (Singapore)" },
    { code: "te", name: "Telugu" },
    { code: "te-IN", name: "Telugu (India)" },
    { code: "tg", name: "Tajik" },
    { code: "th", name: "Thai" },
    { code: "th-TH", name: "Thai (Thailand)" },
    { code: "ti", name: "Tigrinya" },
    { code: "ti-ER", name: "Tigrinya (Eritrea)" },
    { code: "tk", name: "Turkmen" },
    { code: "tl", name: "Tagalog" },
    { code: "tn", name: "Tswana" },
    { code: "tn-BW", name: "Tswana (Botswana)" },
    { code: "to", name: "Tonga" },
    { code: "tr", name: "Turkish" },
    { code: "tr-CY", name: "Turkish (Cyprus)" },
    { code: "tr-TR", name: "Turkish (Turkey)" },
    { code: "ts", name: "Tsonga" },
    { code: "tt", name: "Tatar" },
    { code: "ug", name: "Uyghur" },
    { code: "uk", name: "Ukrainian" },
    { code: "uk-UA", name: "Ukrainian (Ukraine)" },
    { code: "ur", name: "Urdu" },
    { code: "ur-IN", name: "Urdu (India)" },
    { code: "ur-PK", name: "Urdu (Pakistan)" },
    { code: "uz", name: "Uzbek" },
    { code: "uz-Arab", name: "Uzbek (Arabic script)" },
    { code: "uz-Cyrl", name: "Uzbek (Cyrillic script)" },
    { code: "uz-Latn", name: "Uzbek (Latin script)" },
    { code: "ve", name: "Venda" },
    { code: "vi", name: "Vietnamese" },
    { code: "vi-VN", name: "Vietnamese (Vietnam)" },
    { code: "vo", name: "Volapük" },
    { code: "wa", name: "Walloon" },
    { code: "wo", name: "Wolof" },
    { code: "xh", name: "Xhosa" },
    { code: "yi", name: "Yiddish" },
    { code: "yo", name: "Yoruba" },
    { code: "yo-BJ", name: "Yoruba (Benin)" },
    { code: "za", name: "Zhuang" },
    { code: "zh", name: "Chinese" },
    { code: "zh-CH", name: "Chinese (China)" },
    { code: "zh-TW", name: "Chinese (Taiwan)" },
    { code: "zh-Hans", name: "Chinese (Simplified)" },
    { code: "zh-Hans-HK", name: "Chinese (Hong Kong SAR China, Simplified)" },
    { code: "zh-Hans-MO", name: "Chinese (Macao SAR China, Simplified)" },
    { code: "zh-Hans-MY", name: "Chinese (Malaysia, Simplified)" },
    { code: "zh-Hans-SG", name: "Chinese (Singapore, Simplified)" },
    { code: "zh-Hant", name: "Chinese (Traditional)" },
    { code: "zh-Hant-HK", name: "Chinese (Hong Kong SAR China, Traditional)" },
    { code: "zh-Hant-MO", name: "Chinese (Macao SAR China, Traditional)" },
    { code: "zh-Hant-MY", name: "Chinese (Malaysia, Traditional)" },
    { code: "zh-Latn", name: "Chinese (Latin script)" },
    { code: "zu", name: "Zulu" },
    { code: "zu-ZA", name: "Zulu (South Africa)" }
];
